function result = runCollectedCarbonateAssimilation( ...
    opiRoot, experimentRoot, d18OFile, clumpedFile, configFile, outputDir)
% Reweight discrete OPI cases using multi-site carbonate proxy observations.

assimilationRoot = fileparts(fileparts(mfilename('fullpath')));
if nargin < 1 || isempty(opiRoot)
    opiRoot = assimilationRoot;
end
if nargin < 2 || isempty(experimentRoot)
    error('experimentRoot is required and must contain design/case_manifest.csv and calc_only/.');
end
if nargin < 3 || isempty(d18OFile)
    d18OFile = fullfile(assimilationRoot, 'data', 'observations', 'd18O.xlsx');
end
if nargin < 4 || isempty(clumpedFile)
    clumpedFile = fullfile(assimilationRoot, 'data', 'observations', ...
        'clump_temp.xlsx');
end
if nargin < 5 || isempty(configFile)
    configFile = fullfile(assimilationRoot, 'data', 'assimilation', ...
        'collected_carbonate_assimilation_config.csv');
end
if nargin < 6 || isempty(outputDir)
    outputDir = fullfile(assimilationRoot, 'results', ...
        'topography_qiangtang_height_refinement');
end

manifestFile = fullfile(experimentRoot, 'design', 'case_manifest.csv');
terrazasDataFile = fullfile(opiRoot, 'data', 'reference', ...
    'LakeTransferFunction', 'ERA5_LakeTemp.csv');
operatorAssignmentFile = fullfile(assimilationRoot, 'data', 'assimilation', ...
    'observation_operator_assignments.csv');
chronologyFile = fullfile(assimilationRoot, 'data', 'assimilation', ...
    'observation_chronology.csv');
requiredFiles = string({manifestFile, d18OFile, clumpedFile, configFile, ...
    terrazasDataFile, operatorAssignmentFile, chronologyFile});
missing = requiredFiles(~isfile(requiredFiles));
if ~isempty(missing)
    error('Missing collected-proxy assimilation input(s):\n%s', ...
        strjoin(missing, newline));
end
if ~isfolder(outputDir)
    mkdir(outputDir);
end

config = readConfig(configFile);
config.opi_root = string(opiRoot);
config.terrazas_data_csv = string(terrazasDataFile);
manifest = readtable(manifestFile, 'TextType', 'string');
observations = buildObservations(d18OFile, clumpedFile, ...
    operatorAssignmentFile, chronologyFile, config);
numCases = height(manifest);
caseRows = repmat(emptyCaseRow(), numCases, 1);
predictionTables = cell(numCases, 1);

for i = 1:numCases
    caseId = manifest.case_id(i);
    resultFile = fullfile(experimentRoot, 'calc_only', caseId, ...
        'opiCalc_TwoWinds_OxygenOnly_Results.mat');
    if ~isfile(resultFile)
        error('Missing OPI result for case %s: %s', caseId, resultFile);
    end
    [caseRows(i), predictionTables{i}] = evaluateCase( ...
        caseId, manifest(i, :), resultFile, observations, config);
end

predictions = vertcat(predictionTables{:});
casePosterior = struct2table(caseRows);
casePosterior.prior_probability = assignCasePriors(casePosterior, config);
logWeight = casePosterior.log_likelihood_joint + ...
    log(casePosterior.prior_probability);
casePosterior.posterior_probability = normalizeLogWeights(logWeight);
casePosterior.carbonate_only_probability = normalizeLogWeights( ...
    casePosterior.log_likelihood_carbonate + ...
    log(casePosterior.prior_probability));
casePosterior.temperature_only_probability = normalizeLogWeights( ...
    casePosterior.log_likelihood_temperature + ...
    log(casePosterior.prior_probability));
casePosterior.paleosol_only_probability = normalizeLogWeights( ...
    casePosterior.log_likelihood_paleosol + ...
    log(casePosterior.prior_probability));
[~, order] = sort(casePosterior.posterior_probability, 'descend');
casePosterior.posterior_rank = nan(numCases, 1);
casePosterior.posterior_rank(order) = (1:numCases)';
heightPosterior = aggregateHeightPosterior(casePosterior);

writetable(observations, fullfile(outputDir, ...
    'collected_proxy_observations.csv'));
writetable(predictions, fullfile(outputDir, ...
    'collected_proxy_predictions.csv'));
writetable(casePosterior, fullfile(outputDir, ...
    'collected_proxy_case_posterior.csv'));
writetable(heightPosterior, fullfile(outputDir, ...
    'collected_proxy_height_posterior.csv'));
copyfile(configFile, fullfile(outputDir, ...
    'collected_proxy_assimilation_config_snapshot.csv'));
copyfile(operatorAssignmentFile, fullfile(outputDir, ...
    'observation_operator_assignments_snapshot.csv'));
copyfile(chronologyFile, fullfile(outputDir, ...
    'observation_chronology_snapshot.csv'));
makePosteriorFigure(casePosterior, heightPosterior, outputDir);
writeReport(fullfile(outputDir, ...
    'collected_proxy_assimilation_report.md'), observations, predictions, ...
    casePosterior, heightPosterior, config, configFile);

result = struct;
result.status = "provisional_multi_site_proxy_assimilation";
result.observations = observations;
result.predictions = predictions;
result.casePosterior = casePosterior;
result.heightPosterior = heightPosterior;
result.config = config;
result.outputDir = string(outputDir);
save(fullfile(outputDir, 'collected_proxy_assimilation_results.mat'), ...
    'result', '-v7');

fprintf('Wrote collected-proxy assimilation to:\n%s\n', outputDir);
fprintf('Highest-weight case: %s (posterior %.4f)\n', ...
    casePosterior.case_id(order(1)), ...
    casePosterior.posterior_probability(order(1)));
end

function observations = buildObservations( ...
    d18OFile, clumpedFile, operatorAssignmentFile, chronologyFile, config)
d18O = readtable(d18OFile, 'TextType', 'string', ...
    'VariableNamingRule', 'preserve');
clumped = readtable(clumpedFile, 'TextType', 'string', ...
    'VariableNamingRule', 'preserve');
checkColumns(d18O, ["d18O_carbonate", "Uncertainty_2sigma", ...
    "Type", "longitude", "latitude", "Source", "doi"], ...
    'carbonate d18O');
checkColumns(clumped, ["d47_temperature_carbonate", ...
    "Uncertainty_2sigma", "Type", "longitude", "latitude", ...
    "Source", "doi"], 'clumped temperature');

nD18O = height(d18O);
siteId = "site_" + compose('%02d', (1:nD18O)');
source = d18O.Source;
doi = d18O.doi;
proxyType = d18O.Type;
longitude = d18O.longitude;
latitude = d18O.latitude;
d18OVPDB = d18O.d18O_carbonate;
d18OSigma = d18O.Uncertainty_2sigma ./ 2;
clumpedTemperatureC = nan(nD18O, 1);
clumpedTemperatureSigmaC = nan(nD18O, 1);

coordinateTolerance = 1e-6;
matchedClumped = false(height(clumped), 1);
for i = 1:nD18O
    distance = hypot(clumped.longitude - longitude(i), ...
        clumped.latitude - latitude(i));
    sameSource = strcmpi(strtrim(clumped.Source), strtrim(source(i)));
    match = find(distance <= coordinateTolerance & sameSource);
    if numel(match) > 1
        error('Multiple clumped matches for carbonate observation row %d.', i);
    elseif isscalar(match)
        clumpedTemperatureC(i) = clumped.d47_temperature_carbonate(match);
        clumpedTemperatureSigmaC(i) = clumped.Uncertainty_2sigma(match) ./ 2;
        matchedClumped(match) = true;
    end
end

unmatched = find(~matchedClumped);
for j = unmatched'
    siteId(end+1, 1) = "site_" + compose('%02d', numel(siteId) + 1); %#ok<AGROW>
    source(end+1, 1) = clumped.Source(j); %#ok<AGROW>
    doi(end+1, 1) = clumped.doi(j); %#ok<AGROW>
    proxyType(end+1, 1) = clumped.Type(j); %#ok<AGROW>
    longitude(end+1, 1) = clumped.longitude(j); %#ok<AGROW>
    latitude(end+1, 1) = clumped.latitude(j); %#ok<AGROW>
    d18OVPDB(end+1, 1) = nan; %#ok<AGROW>
    d18OSigma(end+1, 1) = nan; %#ok<AGROW>
    clumpedTemperatureC(end+1, 1) = ...
        clumped.d47_temperature_carbonate(j); %#ok<AGROW>
    clumpedTemperatureSigmaC(end+1, 1) = ...
        clumped.Uncertainty_2sigma(j) ./ 2; %#ok<AGROW>
end

hasD18O = isfinite(d18OVPDB) & isfinite(d18OSigma) & d18OSigma > 0;
hasClumpedTemperature = isfinite(clumpedTemperatureC) & ...
    isfinite(clumpedTemperatureSigmaC) & clumpedTemperatureSigmaC > 0;
assignments = readtable(operatorAssignmentFile, 'TextType', 'string', ...
    'Delimiter', ',');
checkColumns(assignments, ["source", "temperature_operator", ...
    "age_min_Ma", "age_max_Ma", "region", "status"], ...
    'observation operator assignments');
if numel(unique(assignments.source)) ~= height(assignments)
    error('Observation operator assignment sources must be unique.');
end
temperatureOperator = repmat("none", numel(source), 1);
operatorAgeMinMa = nan(numel(source), 1);
operatorAgeMaxMa = nan(numel(source), 1);
operatorRegion = repmat("", numel(source), 1);
for i = 1:numel(source)
    match = find(assignments.source == source(i));
    if isscalar(match) && startsWith(lower(assignments.status(match)), "enabled")
        temperatureOperator(i) = assignments.temperature_operator(match);
        operatorAgeMinMa(i) = assignments.age_min_Ma(match);
        operatorAgeMaxMa(i) = assignments.age_max_Ma(match);
        operatorRegion(i) = assignments.region(match);
    end
end
usesLakeOperator = temperatureOperator == "lake_warmest_terrazas2025";
usesPaleosolOperator = (hasD18O | hasClumpedTemperature) & ...
    temperatureOperator == "xiong2022_chattian_paleosol";
chronology = readtable(chronologyFile, 'TextType', 'string', ...
    'Delimiter', ',');
checkColumns(chronology, ["source", "age_mean_Ma", "age_min_Ma", ...
    "age_max_Ma", "age_basis", "chronology_status"], ...
    'observation chronology');
if numel(unique(chronology.source)) ~= height(chronology)
    error('Observation chronology sources must be unique.');
end
ageMeanMa = nan(numel(source), 1);
ageMinMa = nan(numel(source), 1);
ageMaxMa = nan(numel(source), 1);
ageBasis = repmat("not_entered", numel(source), 1);
temporalStatus = repmat("age_unknown", numel(source), 1);
isTemporalEligible = false(numel(source), 1);
ageDistanceToModelMyr = nan(numel(source), 1);
operatorAgeDistanceMyr = zeros(numel(source), 1);
modelAgeMinMa = config.model_time_slice_Ma - ...
    config.model_time_halfwidth_Myr;
modelAgeMaxMa = config.model_time_slice_Ma + ...
    config.model_time_halfwidth_Myr;
for i = 1:numel(source)
    match = find(chronology.source == source(i));
    if ~isscalar(match)
        temporalStatus(i) = "chronology_catalog_missing";
    elseif lower(chronology.chronology_status(match)) == "known"
        ageMeanMa(i) = chronology.age_mean_Ma(match);
        ageMinMa(i) = chronology.age_min_Ma(match);
        ageMaxMa(i) = chronology.age_max_Ma(match);
        ageBasis(i) = chronology.age_basis(match);
        [temporalStatus(i), isTemporalEligible(i), ...
            ageDistanceToModelMyr(i)] = ...
            classifyObservationChronology(ageMinMa(i), ageMaxMa(i), ...
            "known", modelAgeMinMa, modelAgeMaxMa, ...
            config.unknown_age_action);
    else
        ageBasis(i) = chronology.age_basis(match);
        [temporalStatus(i), isTemporalEligible(i), ...
            ageDistanceToModelMyr(i)] = ...
            classifyObservationChronology(nan, nan, "unknown", ...
            modelAgeMinMa, modelAgeMaxMa, config.unknown_age_action);
    end
    if isfinite(ageMinMa(i)) && isfinite(ageMaxMa(i)) && ...
            isfinite(operatorAgeMinMa(i)) && isfinite(operatorAgeMaxMa(i))
        operatorAgeDistanceMyr(i) = ageIntervalDistanceMyr( ...
            ageMinMa(i), ageMaxMa(i), operatorAgeMinMa(i), ...
            operatorAgeMaxMa(i));
    end
end
temperatureReferenceAgeMa = repmat(config.model_time_slice_Ma, ...
    numel(source), 1);
temperatureReferenceAgeMa(usesPaleosolOperator) = ...
    config.xiong2022_reference_age_Ma;
westerholdMeanShiftC = nan(numel(source), 1);
temporalTemperatureSigmaC = nan(numel(source), 1);
temporalWaterD18OSigma = nan(numel(source), 1);
for i = 1:numel(source)
    if ~isTemporalEligible(i) || ...
            ~all(isfinite([ageMinMa(i), ageMaxMa(i)]))
        continue
    end
    temporal = temporalAgeQuadrature(ageMinMa(i), ageMaxMa(i), ...
        temperatureReferenceAgeMa(i), operatorAgeMinMa(i), ...
        operatorAgeMaxMa(i), config);
    westerholdMeanShiftC(i) = sum(temporal.weight .* ...
        temporal.temperatureMeanShiftC);
    temporalTemperatureSigmaC(i) = sqrt(sum(temporal.weight .* ...
        (temporal.temperatureSigmaC.^2 + ...
        (temporal.temperatureMeanShiftC - ...
        westerholdMeanShiftC(i)).^2)));
    temporalWaterD18OSigma(i) = sqrt(sum(temporal.weight .* ...
        temporal.waterD18OSigmaPermil.^2));
end
observations = table(siteId, source, doi, proxyType, longitude, latitude, ...
    d18OVPDB, d18OSigma, clumpedTemperatureC, ...
    clumpedTemperatureSigmaC, hasD18O, hasClumpedTemperature, ...
    temperatureOperator, operatorAgeMinMa, operatorAgeMaxMa, ...
    operatorRegion, ageMeanMa, ageMinMa, ageMaxMa, ageBasis, ...
    ageDistanceToModelMyr, operatorAgeDistanceMyr, ...
    temperatureReferenceAgeMa, westerholdMeanShiftC, ...
    temporalTemperatureSigmaC, temporalWaterD18OSigma, ...
    temporalStatus, isTemporalEligible, usesLakeOperator, ...
    usesPaleosolOperator, ...
    'VariableNames', {'site_id', 'source', 'doi', 'proxy_type', ...
    'longitude', 'latitude', 'd18O_carbonate_VPDB_permil', ...
    'd18O_carbonate_1sigma_permil', 'clumped_temperature_C', ...
    'clumped_temperature_1sigma_C', 'has_d18O', ...
    'has_clumped_temperature', 'temperature_operator', ...
    'operator_age_min_Ma', ...
    'operator_age_max_Ma', 'operator_region', ...
    'age_mean_Ma', 'age_min_Ma', 'age_max_Ma', 'age_basis', ...
    'age_distance_to_model_Myr', 'operator_age_distance_Myr', ...
    'temperature_reference_age_Ma', 'westerhold_mean_shift_C', ...
    'temporal_temperature_sigma_C', ...
    'temporal_water_d18O_sigma_permil', ...
    'temporal_status', 'is_temporally_eligible', 'uses_lake_operator', ...
    'uses_paleosol_operator'});
end

function [caseRow, prediction] = evaluateCase( ...
    caseId, manifestRow, resultFile, observations, config)
S = load(resultFile, 'lon', 'lat', 'd18OGrid', 'pGrid', ...
    'pGrid_1', 'pGrid_2', 'T_1', 'T_2', 'gammaSat_1', ...
    'gammaSat_2', 'topoFile', 'dataPath');
topographyFile = fullfile(S.dataPath, S.topoFile);
P = load(topographyFile, 'hGrid');
hGrid = P.hGrid;

temperature1C = S.T_1(1) - S.gammaSat_1(1) .* hGrid - 273.15;
temperature2C = S.T_2(1) - S.gammaSat_2(1) .* hGrid - 273.15;
airMAATGridC = (S.pGrid_1 .* temperature1C + ...
    S.pGrid_2 .* temperature2C) ./ S.pGrid;
airMAATGridC(~isfinite(airMAATGridC)) = nan;

[lonGrid, latGrid] = meshgrid(S.lon, S.lat);
nObs = height(observations);
insideDomain = observations.longitude >= min(S.lon) & ...
    observations.longitude <= max(S.lon) & ...
    observations.latitude >= min(S.lat) & ...
    observations.latitude <= max(S.lat);
waterD18OPred = nan(nObs, 1);
airMAATPred = nan(nObs, 1);
elevationPredM = nan(nObs, 1);
siteElevationPredM = interp2(S.lon, S.lat, hGrid, ...
    observations.longitude, observations.latitude, 'linear', nan);
nSpatialCells = zeros(nObs, 1);
status = repmat("not_evaluated", nObs, 1);

for j = 1:nObs
    if ~observations.is_temporally_eligible(j)
        status(j) = observations.temporal_status(j);
        continue
    end
    hasSupportedOperator = observations.uses_lake_operator(j) || ...
        observations.uses_paleosol_operator(j);
    if ~hasSupportedOperator && ...
            ~logical(config.include_non_lacustrine)
        status(j) = "unsupported_non_lacustrine_proxy";
        continue
    end
    if ~insideDomain(j)
        status(j) = "outside_model_domain";
        continue
    end
    if observations.uses_paleosol_operator(j)
        if ~isfinite(siteElevationPredM(j))
            status(j) = "no_valid_topography_at_site";
            continue
        end
        elevationPredM(j) = siteElevationPredM(j);
        nSpatialCells(j) = 1;
        if observations.has_d18O(j)
            distanceKm = greatCircleDistanceKm(latGrid, lonGrid, ...
                observations.latitude(j), observations.longitude(j));
            isotopeMask = distanceKm <= config.spatial_radius_km & ...
                isfinite(S.pGrid) & S.pGrid > 0 & ...
                isfinite(S.d18OGrid);
            if ~any(isotopeMask, 'all')
                status(j) = "no_valid_isotope_cells";
                continue
            end
            isotopeWeight = S.pGrid(isotopeMask);
            waterD18OPred(j) = sum(isotopeWeight .* ...
                S.d18OGrid(isotopeMask) .* 1e3) ./ sum(isotopeWeight);
            nSpatialCells(j) = sum(isotopeMask, 'all');
        end
        status(j) = "evaluated_paleosol";
        continue
    end
    distanceKm = greatCircleDistanceKm(latGrid, lonGrid, ...
        observations.latitude(j), observations.longitude(j));
    inRadius = distanceKm <= config.spatial_radius_km;
    temperatureMask = inRadius & isfinite(S.pGrid) & S.pGrid > 0 & ...
        isfinite(airMAATGridC) & isfinite(hGrid);
    if ~any(temperatureMask, 'all')
        status(j) = "no_valid_temperature_cells";
        continue
    end
    temperatureWeight = S.pGrid(temperatureMask);
    airMAATPred(j) = sum(temperatureWeight .* ...
        airMAATGridC(temperatureMask)) ./ sum(temperatureWeight);
    elevationPredM(j) = sum(temperatureWeight .* hGrid(temperatureMask)) ./ ...
        sum(temperatureWeight);
    nSpatialCells(j) = sum(temperatureMask, 'all');

    if observations.has_d18O(j)
        isotopeMask = inRadius & isfinite(S.pGrid) & S.pGrid > 0 & ...
            isfinite(S.d18OGrid);
        if ~any(isotopeMask, 'all')
            status(j) = "no_valid_isotope_cells";
            continue
        end
        isotopeWeight = S.pGrid(isotopeMask);
        waterD18OPred(j) = sum(isotopeWeight .* ...
            S.d18OGrid(isotopeMask) .* 1e3) ./ sum(isotopeWeight);
    end
    status(j) = "evaluated";
end

lakeWarmestPredC = nan(nObs, 1);
sigmaLakeTransferC = nan(nObs, 1);
canPredictTemperature = insideDomain & observations.uses_lake_operator & ...
    isfinite(airMAATPred);
if any(canPredictTemperature)
    [lakeWarmestPredC(canPredictTemperature), ...
        sigmaLakeTransferC(canPredictTemperature)] = ...
        lakeTransferAirToLake_Terrazas2025( ...
        airMAATPred(canPredictTemperature), ...
        observations.latitude(canPredictTemperature), ...
        elevationPredM(canPredictTemperature) ./ 1e3, "warmest", ...
        config.terrazas_data_csv);
end

carbonatePredVPDB = nan(nObs, 1);
carbonateResidual = nan(nObs, 1);
carbonateSigmaTotal = nan(nObs, 1);
carbonateZ = nan(nObs, 1);
temperatureResidual = nan(nObs, 1);
temperatureSigmaTotal = nan(nObs, 1);
temperatureZ = nan(nObs, 1);
logLikelihoodCarbonate = nan(nObs, 1);
logLikelihoodTemperature = nan(nObs, 1);
soilEarlySummerPredC = nan(nObs, 1);
soilSeptemberPredC = nan(nObs, 1);
soilTemperatureResidualC = nan(nObs, 1);
soilTemperatureSigmaC = nan(nObs, 1);
soilTemperatureZ = nan(nObs, 1);
logLikelihoodPaleosol = nan(nObs, 1);
logLikelihoodJoint = zeros(nObs, 1);
isUsed = false(nObs, 1);

for j = 1:nObs
    if status(j) == "evaluated_paleosol"
        temporal = temporalForObservation(observations(j, :), config);
        nAge = numel(temporal.ageMa);
        hasPaleosolTemperature = observations.has_clumped_temperature(j);
        hasPaleosolCarbonate = observations.has_d18O(j) & ...
            isfinite(waterD18OPred(j));
        if ~hasPaleosolTemperature && ~hasPaleosolCarbonate
            continue
        end
        ageLogPaleosol = nan(1, nAge);
        ageLogCarbonate = nan(1, nAge);
        ageEarlySummerC = nan(1, nAge);
        ageSeptemberC = nan(1, nAge);
        ageSoilMeanC = nan(1, nAge);
        ageSoilVarianceC = nan(1, nAge);
        ageCarbonateMean = nan(1, nAge);
        ageCarbonateVariance = nan(1, nAge);
        for k = 1:nAge
            siteConfig = config;
            siteConfig.xiong2022_early_summer_intercept_C = ...
                config.xiong2022_early_summer_intercept_C + ...
                temporal.temperatureMeanShiftC(k);
            siteConfig.xiong2022_september_intercept_C = ...
                config.xiong2022_september_intercept_C + ...
                temporal.temperatureMeanShiftC(k);
            siteConfig.paleosol_temperature_model_discrepancy_C = hypot( ...
                config.paleosol_temperature_model_discrepancy_C, ...
                temporal.temperatureSigmaC(k));
            siteConfig.water_d18O_model_discrepancy_permil = hypot( ...
                config.water_d18O_model_discrepancy_permil, ...
                temporal.waterD18OSigmaPermil(k));
            if hasPaleosolTemperature
                soilDiagnostic = evaluatePaleosolTemperatureOperator( ...
                    observations.temperature_operator(j), ...
                    observations.clumped_temperature_C(j), ...
                    observations.clumped_temperature_1sigma_C(j), ...
                    siteElevationPredM(j), siteConfig);
                ageEarlySummerC(k) = soilDiagnostic.branchTemperatureC(1);
                ageSeptemberC(k) = soilDiagnostic.branchTemperatureC(2);
                ageSoilMeanC(k) = soilDiagnostic.predictedMeanC;
                ageSoilVarianceC(k) = soilDiagnostic.sigmaTotalC.^2;
            end
            if hasPaleosolCarbonate
                soilCarbonateDiagnostic = evaluatePaleosolCarbonateOperator( ...
                    observations.temperature_operator(j), ...
                    observations.d18O_carbonate_VPDB_permil(j), ...
                    observations.d18O_carbonate_1sigma_permil(j), ...
                    waterD18OPred(j), siteElevationPredM(j), siteConfig);
                ageCarbonateMean(k) = ...
                    soilCarbonateDiagnostic.predictedMeanVPDB;
                ageCarbonateVariance(k) = ...
                    soilCarbonateDiagnostic.sigmaTotalVPDB.^2;
                ageLogCarbonate(k) = ...
                    soilCarbonateDiagnostic.logLikelihood;
                if ~hasPaleosolTemperature
                    ageEarlySummerC(k) = ...
                        soilCarbonateDiagnostic.branchTemperatureC(1);
                    ageSeptemberC(k) = ...
                        soilCarbonateDiagnostic.branchTemperatureC(2);
                end
            end
            if hasPaleosolTemperature && hasPaleosolCarbonate
                branchWeight = soilDiagnostic.branchWeight;
                branchLogLikelihood = ...
                    soilDiagnostic.branchLogLikelihood + ...
                    soilCarbonateDiagnostic.branchLogLikelihood - ...
                    log(branchWeight);
                ageLogPaleosol(k) = logSumExp(branchLogLikelihood);
            elseif hasPaleosolTemperature
                ageLogPaleosol(k) = soilDiagnostic.logLikelihood;
            else
                ageLogPaleosol(k) = ...
                    soilCarbonateDiagnostic.logLikelihood;
            end
        end
        logAgeWeight = log(temporal.weight);
        logLikelihoodPaleosol(j) = logSumExp( ...
            ageLogPaleosol + logAgeWeight);
        soilEarlySummerPredC(j) = sum(temporal.weight .* ageEarlySummerC);
        soilSeptemberPredC(j) = sum(temporal.weight .* ageSeptemberC);
        if hasPaleosolTemperature
            soilMeanC = sum(temporal.weight .* ageSoilMeanC);
            soilTemperatureResidualC(j) = ...
                observations.clumped_temperature_C(j) - soilMeanC;
            soilTemperatureSigmaC(j) = sqrt(sum(temporal.weight .* ...
                (ageSoilVarianceC + (ageSoilMeanC - soilMeanC).^2)));
            soilTemperatureZ(j) = soilTemperatureResidualC(j) ./ ...
                soilTemperatureSigmaC(j);
        end
        if hasPaleosolCarbonate
            carbonatePredVPDB(j) = sum(temporal.weight .* ageCarbonateMean);
            carbonateResidual(j) = ...
                observations.d18O_carbonate_VPDB_permil(j) - ...
                carbonatePredVPDB(j);
            carbonateSigmaTotal(j) = sqrt(sum(temporal.weight .* ...
                (ageCarbonateVariance + ...
                (ageCarbonateMean - carbonatePredVPDB(j)).^2)));
            carbonateZ(j) = carbonateResidual(j) ./ carbonateSigmaTotal(j);
            logLikelihoodCarbonate(j) = logSumExp( ...
                ageLogCarbonate + logAgeWeight);
        end
        logLikelihoodJoint(j) = logLikelihoodPaleosol(j);
        isUsed(j) = true;
        continue
    end
    if status(j) ~= "evaluated" || ~isfinite(lakeWarmestPredC(j))
        continue
    end
    hasCarbonate = observations.has_d18O(j) & isfinite(waterD18OPred(j));
    hasTemperature = observations.has_clumped_temperature(j);
    if ~hasCarbonate && ~hasTemperature
        continue
    end
    temporal = temporalForObservation(observations(j, :), config);
    nAge = numel(temporal.ageMa);
    lakeAtAgeC = lakeWarmestPredC(j) + temporal.temperatureMeanShiftC;
    ageLogCarbonate = nan(1, nAge);
    ageLogTemperature = nan(1, nAge);
    ageLogJoint = nan(1, nAge);
    ageCarbonatePred = nan(1, nAge);
    ageCarbonateVariance = nan(1, nAge);
    ageTemperatureVariance = nan(1, nAge);
    for k = 1:nAge
        sigmaTemperatureModel = hypot(hypot(sigmaLakeTransferC(j), ...
            config.temperature_model_discrepancy_C), ...
            temporal.temperatureSigmaC(k));
        if hasCarbonate
            [ageCarbonatePred(k), ~, derivativeTemperature, ...
                derivativeWater] = kimONeil1997CalciteWater( ...
                waterD18OPred(j), lakeAtAgeC(k), ...
                "water_vsmow_to_carbonate_vpdb");
            carbonateResidualAtAge = ...
                observations.d18O_carbonate_VPDB_permil(j) - ...
                ageCarbonatePred(k);
            waterSigma = hypot(config.water_d18O_model_discrepancy_permil, ...
                temporal.waterD18OSigmaPermil(k));
            ageCarbonateVariance(k) = ...
                observations.d18O_carbonate_1sigma_permil(j).^2 + ...
                (derivativeTemperature .* sigmaTemperatureModel).^2 + ...
                (derivativeWater .* waterSigma).^2 + ...
                config.carbonate_fractionation_discrepancy_permil.^2;
            ageLogCarbonate(k) = normalLogLikelihood( ...
                carbonateResidualAtAge, sqrt(ageCarbonateVariance(k)));
        end
        if hasTemperature
            temperatureResidualAtAge = ...
                observations.clumped_temperature_C(j) - lakeAtAgeC(k);
            ageTemperatureVariance(k) = ...
                observations.clumped_temperature_1sigma_C(j).^2 + ...
                sigmaTemperatureModel.^2;
            ageLogTemperature(k) = normalLogLikelihood( ...
                temperatureResidualAtAge, sqrt(ageTemperatureVariance(k)));
        end
        if hasCarbonate && hasTemperature
            covariance = derivativeTemperature .* sigmaTemperatureModel.^2;
            covarianceMatrix = [ageCarbonateVariance(k), covariance; ...
                covariance, ageTemperatureVariance(k)];
            residual = [carbonateResidualAtAge; temperatureResidualAtAge];
            ageLogJoint(k) = multivariateNormalLogLikelihood( ...
                residual, covarianceMatrix);
        elseif hasCarbonate
            ageLogJoint(k) = ageLogCarbonate(k);
        else
            ageLogJoint(k) = ageLogTemperature(k);
        end
    end
    logAgeWeight = log(temporal.weight);
    lakeWarmestPredC(j) = sum(temporal.weight .* lakeAtAgeC);
    if hasCarbonate
        carbonatePredVPDB(j) = sum(temporal.weight .* ageCarbonatePred);
        carbonateResidual(j) = ...
            observations.d18O_carbonate_VPDB_permil(j) - ...
            carbonatePredVPDB(j);
        carbonateSigmaTotal(j) = sqrt(sum(temporal.weight .* ...
            (ageCarbonateVariance + ...
            (ageCarbonatePred - carbonatePredVPDB(j)).^2)));
        carbonateZ(j) = carbonateResidual(j) ./ carbonateSigmaTotal(j);
        logLikelihoodCarbonate(j) = logSumExp( ...
            ageLogCarbonate + logAgeWeight);
    end
    if hasTemperature
        temperatureResidual(j) = observations.clumped_temperature_C(j) - ...
            lakeWarmestPredC(j);
        temperatureSigmaTotal(j) = sqrt(sum(temporal.weight .* ...
            (ageTemperatureVariance + ...
            (lakeAtAgeC - lakeWarmestPredC(j)).^2)));
        temperatureZ(j) = temperatureResidual(j) ./ ...
            temperatureSigmaTotal(j);
        logLikelihoodTemperature(j) = logSumExp( ...
            ageLogTemperature + logAgeWeight);
    end
    logLikelihoodJoint(j) = logSumExp(ageLogJoint + logAgeWeight);
    isUsed(j) = true;
end

prediction = table(repmat(string(caseId), nObs, 1), ...
    observations.site_id, observations.source, observations.longitude, ...
    observations.latitude, observations.has_d18O, ...
    observations.has_clumped_temperature, ...
    observations.temperature_operator, observations.age_mean_Ma, ...
    observations.age_min_Ma, observations.age_max_Ma, ...
    observations.age_distance_to_model_Myr, ...
    observations.operator_age_distance_Myr, ...
    observations.temperature_reference_age_Ma, ...
    observations.westerhold_mean_shift_C, ...
    observations.temporal_temperature_sigma_C, ...
    observations.temporal_water_d18O_sigma_permil, ...
    observations.temporal_status, observations.is_temporally_eligible, ...
    observations.uses_lake_operator, ...
    observations.uses_paleosol_operator, insideDomain, isUsed, status, ...
    repmat(config.spatial_radius_km, nObs, 1), nSpatialCells, ...
    elevationPredM, siteElevationPredM, airMAATPred, lakeWarmestPredC, ...
    sigmaLakeTransferC, ...
    waterD18OPred, carbonatePredVPDB, ...
    observations.d18O_carbonate_VPDB_permil, carbonateResidual, ...
    carbonateSigmaTotal, carbonateZ, observations.clumped_temperature_C, ...
    temperatureResidual, temperatureSigmaTotal, temperatureZ, ...
    soilEarlySummerPredC, soilSeptemberPredC, ...
    soilTemperatureResidualC, soilTemperatureSigmaC, soilTemperatureZ, ...
    logLikelihoodCarbonate, logLikelihoodTemperature, ...
    logLikelihoodPaleosol, logLikelihoodJoint, ...
    'VariableNames', {'case_id', 'site_id', 'source', 'longitude', ...
    'latitude', 'has_d18O', 'has_clumped_temperature', ...
    'temperature_operator', 'age_mean_Ma', 'age_min_Ma', 'age_max_Ma', ...
    'age_distance_to_model_Myr', 'operator_age_distance_Myr', ...
    'temperature_reference_age_Ma', 'westerhold_mean_shift_C', ...
    'temporal_temperature_sigma_C', ...
    'temporal_water_d18O_sigma_permil', ...
    'temporal_status', 'is_temporally_eligible', 'uses_lake_operator', ...
    'uses_paleosol_operator', ...
    'inside_model_domain', 'is_used', 'status', 'spatial_radius_km', ...
    'n_spatial_cells', 'predicted_elevation_m', ...
    'predicted_site_elevation_m', ...
    'predicted_air_MAAT_C', 'predicted_lake_warmest_C', ...
    'sigma_lake_transfer_C', 'predicted_water_d18O_VSMOW_permil', ...
    'predicted_carbonate_d18O_VPDB_permil', ...
    'observed_carbonate_d18O_VPDB_permil', ...
    'carbonate_residual_permil', 'carbonate_sigma_total_permil', ...
    'carbonate_z', ...
    'observed_clumped_temperature_C', 'temperature_residual_C', ...
    'temperature_sigma_total_C', 'temperature_z', ...
    'predicted_soil_early_summer_C', 'predicted_soil_september_C', ...
    'paleosol_temperature_residual_C', ...
    'paleosol_temperature_sigma_total_C', 'paleosol_temperature_z', ...
    'log_likelihood_carbonate', 'log_likelihood_temperature', ...
    'log_likelihood_paleosol', 'log_likelihood_joint'});

caseRow = emptyCaseRow();
caseRow.case_id = string(caseId);
caseRow.gangdese_target_m = manifestRow.gangdese_target_m;
caseRow.qiangtang_target_m = manifestRow.qiangtang_target_m;
caseRow.valley_mode = manifestRow.valley_mode;
caseRow.n_observations_total = nObs;
caseRow.n_observations_used = sum(isUsed);
caseRow.n_carbonate_used = sum(isUsed & observations.has_d18O);
caseRow.n_temperature_used = sum(isUsed & ...
    observations.has_clumped_temperature & observations.uses_lake_operator);
caseRow.n_paleosol_used = sum(isUsed & ...
    observations.uses_paleosol_operator);
caseRow.log_likelihood_carbonate = sum( ...
    logLikelihoodCarbonate(isUsed & observations.has_d18O));
caseRow.log_likelihood_temperature = sum( ...
    logLikelihoodTemperature(isUsed & ...
    observations.has_clumped_temperature & observations.uses_lake_operator));
caseRow.log_likelihood_paleosol = sum( ...
    logLikelihoodPaleosol(isUsed & observations.uses_paleosol_operator));
caseRow.log_likelihood_joint = sum(logLikelihoodJoint(isUsed));
caseRow.mean_abs_carbonate_residual_permil = mean( ...
    abs(carbonateResidual(isUsed & observations.has_d18O)), 'omitnan');
caseRow.mean_abs_temperature_residual_C = mean( ...
    abs(temperatureResidual(isUsed & ...
    observations.has_clumped_temperature & ...
    observations.uses_lake_operator)), 'omitnan');
caseRow.mean_abs_paleosol_temperature_residual_C = mean( ...
    abs(soilTemperatureResidualC(isUsed & ...
    observations.uses_paleosol_operator)), 'omitnan');
caseRow.max_abs_carbonate_z = max(abs( ...
    carbonateZ(isUsed & observations.has_d18O)), [], 'omitnan');
caseRow.n_carbonate_abs_z_gt3 = sum(abs( ...
    carbonateZ(isUsed & observations.has_d18O)) > 3);
caseRow.max_abs_temperature_z = max(abs( ...
    temperatureZ(isUsed & observations.has_clumped_temperature)), ...
    [], 'omitnan');
caseRow.max_abs_paleosol_temperature_z = max(abs( ...
    soilTemperatureZ(isUsed & observations.uses_paleosol_operator)), ...
    [], 'omitnan');
caseRow.result_file = string(resultFile);
end

function config = readConfig(configFile)
importOptions = detectImportOptions(configFile, 'TextType', 'string');
importOptions = setvartype(importOptions, {'key', 'value'}, 'string');
T = readtable(configFile, importOptions);
checkColumns(T, ["key", "value"], 'assimilation config');
config = struct;
for i = 1:height(T)
    key = char(T.key(i));
    numericValue = str2double(T.value(i));
    if isfinite(numericValue)
        config.(key) = numericValue;
    else
        config.(key) = T.value(i);
    end
end
end

function checkColumns(T, required, label)
missing = setdiff(required, string(T.Properties.VariableNames));
if ~isempty(missing)
    error('Missing %s column(s): %s', label, strjoin(missing, ', '));
end
end

function temporal = temporalForObservation(observation, config)
if all(isfinite([observation.age_min_Ma, observation.age_max_Ma]))
    ageMinMa = observation.age_min_Ma;
    ageMaxMa = observation.age_max_Ma;
else
    ageMinMa = config.model_time_slice_Ma;
    ageMaxMa = config.model_time_slice_Ma;
end
if observation.uses_paleosol_operator
    referenceAgeMa = config.xiong2022_reference_age_Ma;
else
    referenceAgeMa = config.model_time_slice_Ma;
end
temporal = temporalAgeQuadrature(ageMinMa, ageMaxMa, referenceAgeMa, ...
    observation.operator_age_min_Ma, observation.operator_age_max_Ma, ...
    config);
end

function distanceKm = greatCircleDistanceKm(lat, lon, centerLat, centerLon)
radiusEarthKm = 6371;
dLat = deg2rad(lat - centerLat);
dLon = deg2rad(lon - centerLon);
a = sin(dLat ./ 2).^2 + cosd(lat) .* cosd(centerLat) .* ...
    sin(dLon ./ 2).^2;
distanceKm = 2 .* radiusEarthKm .* asin(min(1, sqrt(a)));
end

function value = normalLogLikelihood(residual, sigma)
value = -0.5 .* (residual ./ sigma).^2 - log(sigma) - 0.5 .* log(2*pi);
end

function value = logSumExp(logValues)
maximum = max(logValues, [], 'all');
value = maximum + log(sum(exp(logValues - maximum), 'all'));
end

function value = multivariateNormalLogLikelihood(residual, covariance)
[R, flag] = chol(covariance);
if flag ~= 0
    error('Proxy likelihood covariance is not positive definite.');
end
standardized = R' \ residual;
value = -0.5 .* (standardized' * standardized) - ...
    sum(log(diag(R))) - numel(residual) ./ 2 .* log(2*pi);
end

function prior = assignCasePriors(casePosterior, config)
n = height(casePosterior);
prior = zeros(n, 1);
switch lower(string(config.case_prior_type))
    case {"uniform", "uniform_case"}
        prior(:) = 1 ./ n;
    case "uniform_qiangtang_height_then_case"
        heights = unique(casePosterior.qiangtang_target_m);
        for i = 1:numel(heights)
            keep = casePosterior.qiangtang_target_m == heights(i);
            prior(keep) = 1 ./ numel(heights) ./ sum(keep);
        end
    otherwise
        error('Unsupported case prior: %s', config.case_prior_type);
end
end

function weight = normalizeLogWeights(logWeight)
maximum = max(logWeight);
weight = exp(logWeight - maximum);
weight = weight ./ sum(weight);
end

function heightPosterior = aggregateHeightPosterior(casePosterior)
[heightM, ~, group] = unique(casePosterior.qiangtang_target_m);
priorProbability = accumarray(group, casePosterior.prior_probability, ...
    [numel(heightM), 1], @sum, 0);
posteriorProbability = accumarray(group, ...
    casePosterior.posterior_probability, [numel(heightM), 1], @sum, 0);
carbonateOnlyProbability = accumarray(group, ...
    casePosterior.carbonate_only_probability, ...
    [numel(heightM), 1], @sum, 0);
temperatureOnlyProbability = accumarray(group, ...
    casePosterior.temperature_only_probability, ...
    [numel(heightM), 1], @sum, 0);
paleosolOnlyProbability = accumarray(group, ...
    casePosterior.paleosol_only_probability, ...
    [numel(heightM), 1], @sum, 0);
heightPosterior = table(heightM, priorProbability, posteriorProbability, ...
    carbonateOnlyProbability, temperatureOnlyProbability, ...
    paleosolOnlyProbability, ...
    'VariableNames', {'qiangtang_height_m', 'prior_probability', ...
    'posterior_probability', 'carbonate_only_probability', ...
    'temperature_only_probability', 'paleosol_only_probability'});
heightPosterior = sortrows(heightPosterior, 'qiangtang_height_m');
end

function row = emptyCaseRow()
row = struct('case_id', "", 'gangdese_target_m', nan, ...
    'qiangtang_target_m', nan, 'valley_mode', "", ...
    'n_observations_total', nan, 'n_observations_used', nan, ...
    'n_carbonate_used', nan, 'n_temperature_used', nan, ...
    'n_paleosol_used', nan, ...
    'log_likelihood_carbonate', nan, ...
    'log_likelihood_temperature', nan, ...
    'log_likelihood_paleosol', nan, ...
    'log_likelihood_joint', nan, ...
    'mean_abs_carbonate_residual_permil', nan, ...
    'mean_abs_temperature_residual_C', nan, ...
    'mean_abs_paleosol_temperature_residual_C', nan, ...
    'max_abs_carbonate_z', nan, 'n_carbonate_abs_z_gt3', nan, ...
    'max_abs_temperature_z', nan, ...
    'max_abs_paleosol_temperature_z', nan, 'result_file', "", ...
    'prior_probability', nan, 'posterior_probability', nan, ...
    'carbonate_only_probability', nan, ...
    'temperature_only_probability', nan, ...
    'paleosol_only_probability', nan, 'posterior_rank', nan);
end

function makePosteriorFigure(casePosterior, heightPosterior, outputDir)
fig = figure('Color', 'w', 'Name', 'Collected carbonate proxy assimilation', ...
    'Position', [100, 100, 1500, 650]);
tiledlayout(fig, 1, 2);
ax1 = nexttile;
if isprop(ax1, 'Toolbar') && ~isempty(ax1.Toolbar)
    ax1.Toolbar.Visible = 'off';
end
bar(ax1, categorical(casePosterior.case_id), ...
    casePosterior.posterior_probability, 'FaceColor', [0.15, 0.48, 0.65]);
grid(ax1, 'on');
ylabel(ax1, 'Posterior probability');
title(ax1, 'Topography cases');
ax1.XTickLabelRotation = 60;

ax2 = nexttile;
if isprop(ax2, 'Toolbar') && ~isempty(ax2.Toolbar)
    ax2.Toolbar.Visible = 'off';
end
plot(ax2, heightPosterior.qiangtang_height_m, ...
    heightPosterior.prior_probability, '--o', 'LineWidth', 1.5, ...
    'DisplayName', 'Prior');
hold(ax2, 'on');
plot(ax2, heightPosterior.qiangtang_height_m, ...
    heightPosterior.posterior_probability, '-s', 'LineWidth', 2, ...
    'DisplayName', 'Posterior');
plot(ax2, heightPosterior.qiangtang_height_m, ...
    heightPosterior.carbonate_only_probability, ':^', 'LineWidth', 1.4, ...
    'DisplayName', 'Carbonate only');
plot(ax2, heightPosterior.qiangtang_height_m, ...
    heightPosterior.temperature_only_probability, '-.d', 'LineWidth', 1.4, ...
    'DisplayName', 'Temperature only');
plot(ax2, heightPosterior.qiangtang_height_m, ...
    heightPosterior.paleosol_only_probability, '--v', 'LineWidth', 1.4, ...
    'DisplayName', 'Paleosol only');
grid(ax2, 'on');
xlabel(ax2, 'Qiangtang height (m)');
ylabel(ax2, 'Probability');
title(ax2, 'Height posterior');
legend(ax2, 'Location', 'best');
exportgraphics(fig, fullfile(outputDir, ...
    'Fig_CollectedProxy_Assimilation.png'), 'Resolution', 220);
savefig(fig, fullfile(outputDir, 'Fig_CollectedProxy_Assimilation.fig'));
close(fig);
end

function writeReport(reportFile, observations, predictions, ...
    casePosterior, heightPosterior, config, configFile)
fid = fopen(reportFile, 'w');
if fid == -1
    error('Could not create assimilation report: %s', reportFile);
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
[~, best] = max(casePosterior.posterior_probability);
bestPredictions = predictions(predictions.case_id == ...
    casePosterior.case_id(best), :);

fprintf(fid, '# Collected Carbonate Proxy Assimilation\n\n');
fprintf(fid, '> Status: provisional discrete-ensemble data assimilation.\n\n');
fprintf(fid, 'The observation operator maps OPI precipitation d18O and ');
fprintf(fid, 'surface-air MAAT to warmest lake temperature and then to ');
fprintf(fid, ['carbonate d18O using Kim and O''Neil (1997). Paleosol ' ...
    'clumped temperatures use a separate formation-temperature operator ' ...
    'and never enter the lake transfer function.\n\n']);
fprintf(fid, '## Observation operator\n\n');
fprintf(fid, '- Spatial support radius: %.1f km, precipitation weighted.\n', ...
    config.spatial_radius_km);
fprintf(fid, '- Water d18O model discrepancy: %.2f per mil.\n', ...
    config.water_d18O_model_discrepancy_permil);
fprintf(fid, '- Carbonate fractionation discrepancy: %.2f per mil.\n', ...
    config.carbonate_fractionation_discrepancy_permil);
fprintf(fid, '- Temperature model discrepancy: %.2f C.\n\n', ...
    config.temperature_model_discrepancy_C);
fprintf(fid, '- Nominal model age: %.1f Ma.\n', config.model_time_slice_Ma);
fprintf(fid, ['- Westerhold temperature decrease from %.1f to %.1f Ma: ' ...
    '%.2f +/- %.2f C.\n'], config.westerhold_old_age_Ma, ...
    config.westerhold_young_age_Ma, ...
    config.westerhold_temperature_change_C, ...
    config.westerhold_temperature_change_1sigma_C);
fprintf(fid, '- Regional response: %.2f +/- %.2f.\n', ...
    config.westerhold_regional_response_mean, ...
    config.westerhold_regional_response_1sigma);
fprintf(fid, '- Uniform age quadrature nodes per study: %d.\n', ...
    round(config.age_quadrature_nodes));
fprintf(fid, '- Residual temporal temperature rate: %.2f C/Myr.\n', ...
    config.temporal_temperature_rate_C_per_Myr);
fprintf(fid, '- Temporal water d18O rate: %.2f per mil/Myr.\n', ...
    config.temporal_water_d18O_rate_permil_per_Myr);
fprintf(fid, '- Paleosol operator extrapolation rate: %.2f C/Myr.\n\n', ...
    config.temporal_operator_extrapolation_rate_C_per_Myr);
fprintf(fid, ['- Xiong 2022 paleosol operator: early summer ' ...
    '`36.5 - 5.0 * elevation_km` C; September ' ...
    '`37.0 - 6.0 * elevation_km` C.\n']);
fprintf(fid, '- Paleosol structural discrepancy: %.2f C.\n', ...
    config.paleosol_temperature_model_discrepancy_C);
fprintf(fid, ['- Additional paleosol soil-water versus precipitation ' ...
    'd18O discrepancy: %.2f per mil (zero mean correction).\n'], ...
    config.paleosol_soil_water_discrepancy_permil);
fprintf(fid, ['- The two paleosol formation-season likelihoods are ' ...
    'marginalized; observed temperature is not first inverted to one ' ...
    'elevation.\n\n']);

fprintf(fid, '## Observations\n\n');
fprintf(fid, '- Total proxy sites: %d.\n', height(observations));
fprintf(fid, '- Carbonate d18O sites: %d.\n', sum(observations.has_d18O));
fprintf(fid, '- Clumped-temperature sites: %d.\n', ...
    sum(observations.has_clumped_temperature));
fprintf(fid, '- Sites assigned to the lake operator: %d.\n', ...
    sum(observations.uses_lake_operator));
fprintf(fid, '- Sites assigned to a paleosol operator: %d.\n', ...
    sum(observations.uses_paleosol_operator));
fprintf(fid, '- Age intervals containing the nominal model age: %d.\n', ...
    sum(observations.temporal_status == ...
    "age_interval_contains_model_time"));
fprintf(fid, '- Age-offset sites retained with inflated uncertainty: %d.\n', ...
    sum(observations.temporal_status == ...
    "age_offset_uncertainty_inflated"));
fprintf(fid, '- Sites with unknown age included provisionally: %d.\n', ...
    sum(observations.temporal_status == "age_unknown_provisional_include"));
fprintf(fid, '- Sites excluded for missing chronology or operator: %d.\n', ...
    sum(~observations.is_temporally_eligible));
fprintf(fid, '- Best-case observations used: %d.\n\n', ...
    sum(bestPredictions.is_used));
fprintf(fid, ['| Source | Age min Ma | Age max Ma | Distance to 30 Ma ' ...
    'Myr | Operator distance Myr | Mean Westerhold shift C | ' ...
    'Marginal sigma T C | Marginal sigma d18O |\n']);
fprintf(fid, '|---|---:|---:|---:|---:|---:|---:|---:|\n');
for i = 1:height(observations)
    fprintf(fid, ['| %s | %.1f | %.1f | %.1f | %.1f | %.2f | ' ...
        '%.2f | %.2f |\n'], ...
        observations.source(i), observations.age_min_Ma(i), ...
        observations.age_max_Ma(i), ...
        observations.age_distance_to_model_Myr(i), ...
        observations.operator_age_distance_Myr(i), ...
        observations.westerhold_mean_shift_C(i), ...
        observations.temporal_temperature_sigma_C(i), ...
        observations.temporal_water_d18O_sigma_permil(i));
end
fprintf(fid, '\n');

fprintf(fid, '## Posterior\n\n');
fprintf(fid, '- Highest-weight case: `%s`.\n', casePosterior.case_id(best));
fprintf(fid, '- Posterior probability: %.4f.\n', ...
    casePosterior.posterior_probability(best));
fprintf(fid, '- Mean absolute carbonate residual: %.3f per mil.\n', ...
    casePosterior.mean_abs_carbonate_residual_permil(best));
fprintf(fid, '- Mean absolute temperature residual: %.3f C.\n\n', ...
    casePosterior.mean_abs_temperature_residual_C(best));
fprintf(fid, '- Mean absolute paleosol temperature residual: %.3f C.\n', ...
    casePosterior.mean_abs_paleosol_temperature_residual_C(best));
fprintf(fid, '- Maximum absolute carbonate z score: %.2f.\n', ...
    casePosterior.max_abs_carbonate_z(best));
fprintf(fid, '- Carbonate observations beyond 3 sigma: %d.\n', ...
    casePosterior.n_carbonate_abs_z_gt3(best));
fprintf(fid, '- Maximum absolute temperature z score: %.2f.\n\n', ...
    casePosterior.max_abs_temperature_z(best));
fprintf(fid, '- Maximum absolute paleosol temperature z score: %.2f.\n\n', ...
    casePosterior.max_abs_paleosol_temperature_z(best));
if casePosterior.n_carbonate_abs_z_gt3(best) > 0
    fprintf(fid, ['The posterior ranks the tested cases, but the best case ' ...
        'does not provide an adequate absolute fit to every carbonate ' ...
        'observation. Inspect the site diagnostics before interpreting ' ...
        'the posterior as a validated elevation estimate.\n\n']);
end

fprintf(fid, ['| Height m | Prior | Joint | Carbonate only | ' ...
    'Lake temperature only | Paleosol only |\n']);
fprintf(fid, '|---:|---:|---:|---:|---:|---:|\n');
for i = 1:height(heightPosterior)
    fprintf(fid, '| %.0f | %.4f | %.4f | %.4f | %.4f | %.4f |\n', ...
        heightPosterior.qiangtang_height_m(i), ...
        heightPosterior.prior_probability(i), ...
        heightPosterior.posterior_probability(i), ...
        heightPosterior.carbonate_only_probability(i), ...
        heightPosterior.temperature_only_probability(i), ...
        heightPosterior.paleosol_only_probability(i));
end
fprintf(fid, '\n## Best-case site diagnostics\n\n');
fprintf(fid, ['| Source | Operator | Used | Water d18O | Carbonate ' ...
    'residual | Carbonate z | Lake T residual | Lake T z | Paleosol T ' ...
    'residual | Paleosol T z | Status |\n']);
fprintf(fid, '|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---|\n');
for i = 1:height(bestPredictions)
    fprintf(fid, ['| %s | %s | %d | %.3f | %.3f | %.3f | %.3f | ' ...
        '%.3f | %.3f | %.3f | %s |\n'], ...
        bestPredictions.source(i), bestPredictions.temperature_operator(i), ...
        bestPredictions.is_used(i), ...
        bestPredictions.predicted_water_d18O_VSMOW_permil(i), ...
        bestPredictions.carbonate_residual_permil(i), ...
        bestPredictions.carbonate_z(i), ...
        bestPredictions.temperature_residual_C(i), ...
        bestPredictions.temperature_z(i), ...
        bestPredictions.paleosol_temperature_residual_C(i), ...
        bestPredictions.paleosol_temperature_z(i), ...
        bestPredictions.status(i));
end
fprintf(fid, '\nConfiguration source: `%s`.\n', configFile);
end
